-- +goose Up

-- Crawl-depth instrumentation (frontier-mining audit, 2026-07-24). discovered_depth
-- records the depth (hops from the seed) of the source page a crawl-lane listing was
-- extracted from, so the frontier maxDepth cap can be tuned from where postings are
-- actually found. Nullable: the ATS Fetch lane has no crawl depth and leaves it NULL.
ALTER TABLE job_listing ADD COLUMN discovered_depth integer;

-- Re-tune the singleton Collection definition (migration 0019) from the same audit:
--   * max_depth 10 -> 7: the deep tail is reached via cross-linking into non-job
--     content, not by postings living deep (93% of crawl listings sit within +3 path
--     levels of their seed); 7 keeps margin while capping the sprawl.
--   * url_filter: adds blockedQueryParams (TYPO3 tx_*, cache/session traps) and German
--     editorial/event/media path segments that dominate university/government frontiers
--     yet never hold a posting.
-- The JSON is the marshaled form of crawler.DefaultCollectionURLFilterConfig(); the
-- testcontainers parity assertion pins the two together so they cannot drift.
UPDATE crawl_definition
SET max_depth = 7,
    url_filter = '{"allowedTLDs":["de","com","org","ai","io","jobs","eu","tech","sh","app","dev","cafe","health","xyz"],"blockedSubdomains":["apps","wiki","foundation","docs","donate","shop","store","marketplace","help","support","forum","community","research","discuss","gist","templates","api","books","cdn","static","assets","status","staging","dev","test","login","auth","sso","accounts","id","ads","mail","email","analytics","tracking","events"],"blockedPathSegments":["add_to","wiki","signin","users","podcast","learning","products","imprint","impressum","contact","privacy","legal","terms","disclaimer","cookie","gdpr","tos","agb","datenschutz","login","signup","register","auth","oauth","sso","account","profile","settings","password","logout","shop","store","cart","checkout","pricing","plans","billing","subscribe","order","help","support","faq","docs","documentation","forum","community","knowledgebase","comments","share","feed","rss","atom","sitemap","social","assets","static","cdn","download","downloads","api","webhook","graphql","landing","promo","campaign","ads","referral","affiliate","events","webinar","top-content","maps","demo","trial","onboarding","tour","features","integrations","changelog","roadmap","status","model","workflows","cgi","cdn-cgi","authenticate","games","wp-content","wp-json","wp-includes","wp-admin","uploads","fileadmin","plugins","themes","category","categories","tag","tags","author","authors","archive","archives","search","blog","news","press","media","articles","article","stories","story","posts","post","magazine","presse","aktuelles","pressemitteilungen","meldungen","mitteilungen","veranstaltung","veranstaltungen","termine","kalender","galerie","gallery","publikationen","veroeffentlichungen","publications"],"blockedHostnames":["www.addtoany.com","trustpilot.com","www.apple.com","x.com","www.x.com","youtube.com","www.youtube.com","youtu.be","www.youtu.be","foundation.wikimedia.com","github.com","www.github.com","tiktok.com","www.tiktok.com","twitter.com","www.twitter.com","roboflow.com","www.roboflow.com","instagram.com","www.instagram.com","google.com","www.google.com","bing.com","www.bing.com","open.spotify"],"blockedFileExtensions":["pdf","doc","docx","xls","xlsx","ppt","pptx","odt","ods","odp","rtf","csv","jpg","jpeg","png","gif","svg","webp","bmp","ico","tif","tiff","zip","rar","gz","tar","7z","bz2","dmg","exe","pkg","mp4","mp3","mov","avi","wmv","m4a","m4v","wav","ogg","webm","flv","mkv","m3u","m3u8","woff","woff2","ttf","otf","eot"],"blockedQueryParams":["tx_*","no_cache","phpsessid","jsessionid","sessionid","replytocom"],"passSubdomains":["jobs","career","careers","karriere","hiring","recruiting","talent","join","apply","boards","team","job-boards"],"passPathSegments":["jobs","job","careers","career","karriere","vacancies","positions","openings","apply","hiring","opportunities","recruitment","stellenangebote","stellen","team"]}'::jsonb
WHERE id = '00000000-0000-0000-0000-00000c011ec7';

-- +goose Down

UPDATE crawl_definition
SET max_depth = 10,
    url_filter = '{"allowedTLDs":["de","com","org","ai","io","jobs","eu","tech","sh","app","dev","cafe","health","xyz"],"blockedSubdomains":["apps","wiki","foundation","docs","donate","shop","store","marketplace","help","support","forum","community","research","discuss","gist","templates","api","books","cdn","static","assets","status","staging","dev","test","login","auth","sso","accounts","id","ads","mail","email","analytics","tracking","events"],"blockedPathSegments":["add_to","wiki","signin","users","podcast","learning","products","imprint","impressum","contact","privacy","legal","terms","disclaimer","cookie","gdpr","tos","agb","datenschutz","login","signup","register","auth","oauth","sso","account","profile","settings","password","logout","shop","store","cart","checkout","pricing","plans","billing","subscribe","order","help","support","faq","docs","documentation","forum","community","knowledgebase","comments","share","feed","rss","atom","sitemap","social","assets","static","cdn","download","downloads","api","webhook","graphql","landing","promo","campaign","ads","referral","affiliate","events","webinar","top-content","maps","demo","trial","onboarding","tour","features","integrations","changelog","roadmap","status","model","workflows","cgi","cdn-cgi","authenticate","games","wp-content","wp-json","wp-includes","wp-admin","uploads","fileadmin","plugins","themes","category","categories","tag","tags","author","authors","archive","archives","search","blog","news","press","media","articles","article","stories","story","posts","post","magazine"],"blockedHostnames":["www.addtoany.com","trustpilot.com","www.apple.com","x.com","www.x.com","youtube.com","www.youtube.com","youtu.be","www.youtu.be","foundation.wikimedia.com","github.com","www.github.com","tiktok.com","www.tiktok.com","twitter.com","www.twitter.com","roboflow.com","www.roboflow.com","instagram.com","www.instagram.com","google.com","www.google.com","bing.com","www.bing.com","open.spotify"],"blockedFileExtensions":["pdf","doc","docx","xls","xlsx","ppt","pptx","odt","ods","odp","rtf","csv","jpg","jpeg","png","gif","svg","webp","bmp","ico","tif","tiff","zip","rar","gz","tar","7z","bz2","dmg","exe","pkg","mp4","mp3","mov","avi","wmv","m4a","m4v","wav","ogg","webm","flv","mkv","m3u","m3u8","woff","woff2","ttf","otf","eot"],"passSubdomains":["jobs","career","careers","karriere","hiring","recruiting","talent","join","apply","boards","team","job-boards"],"passPathSegments":["jobs","job","careers","career","karriere","vacancies","positions","openings","apply","hiring","opportunities","recruitment","stellenangebote","stellen","team"]}'::jsonb
WHERE id = '00000000-0000-0000-0000-00000c011ec7';

ALTER TABLE job_listing DROP COLUMN discovered_depth;
