// This file is the Extract Gold Set's BOUNDARY drawings (ADR-0043 #263, ADR-0049
// #304): the pairs of gate configs whose disagreement DEFINES each Boundary
// Stratum, the streaming replay that computes that disagreement over a capture
// frame, the shared draw both verbs run, and the human confirmation sheet the
// strata's labels are owed. It replays the real Extract Gate and nothing else --
// no network, no model, no crawler behaviour.
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"sort"
	"strings"
	"time"

	"github.com/nicholasbraun/job-crawler-poc/cmd/llmbench/bench"
	crawler "github.com/nicholasbraun/job-crawler-poc/internal"
	"github.com/nicholasbraun/job-crawler-poc/internal/pagegate"
)

// boundaryCensusWeight is a CENSUS boundary drawing's row weight. It is exactly 1
// because every page the drawing's half of the disagreement holds is taken, so each
// row's inclusion probability is 1 and its inverse is 1. There is no accept-share
// correction to apply -- a census describes no stream, so there is no population to
// weight toward -- and the per-drawing weight balance therefore holds by construction.
//
// It is NOT every Boundary Stratum row's weight. A STRATIFIED Boundary Stratum
// (selectionStratified, ADR-0049) samples its bands, so its rows carry the inverse of
// their own selection probability, normalized to the drawing's row count. Weighting a
// sampled row 1 anyway would make any weighted read over the stratum describe the
// enriched sample while claiming to describe the drop set. A band whose quota does not
// bind is the one case where the two coincide, and it coincides by arithmetic rather
// than by exception: taking a band whole makes N_c/n_c exactly 1.
const boundaryCensusWeight = 1.0

// selectionDesign is HOW a boundary design turns the disagreement into rows. It is a
// field of the design rather than a flag, for boundaryCandidateConfig's reason: a
// stratum is claimed by exactly one design and therefore by exactly one selection
// design, which is how a committed row states not just which PAIR drew it but under
// which inclusion probabilities. Mixing two selection designs inside one stratum is
// what makes a weighted estimate over it unrecoverable.
type selectionDesign string

const (
	// selectionCensus takes every page of the half the design draws, at
	// boundaryCensusWeight.
	selectionCensus selectionDesign = "census"
	// selectionStratified samples the drop set in bands and weights each row by the
	// inverse of its selection probability (ADR-0049).
	selectionStratified selectionDesign = "stratified"
)

// boundaryBands is the fixed print / iteration order of a stratified drawing's bands.
// The order is the argument's: the live-accept half first, then the two score bands from
// the cut downwards.
var boundaryBands = []goldBand{bandAccepted, bandNear, bandDeep}

const (
	// defaultVetoNearBand is the score width below pagegate.VetoThreshold that counts
	// as "just below the cut". It is a FLAG's default rather than a constant use: what
	// the bands MEAN is the design and may not drift, but where "near" ends is a
	// judgement an operator re-reads off the report's band populations.
	//
	// The judgement is stated as a SHARE of the sub-threshold range rather than as an
	// absolute score, because the threshold is regenerated by every refit while an
	// absolute width is not. A width that outlives its threshold does not merely lose
	// its meaning: validate() refuses a band at or above the cut, so the verb's own
	// default becomes ILLEGAL the moment a refit lands below it -- which is exactly what
	// happened when the Extract Gold Set grew to 737 rows and the cut fell from 0.605395
	// to 0.165048. docs/improving-the-posting-score.md names that failure mode outright.
	//
	// A third is not a new judgement. The 0.20 this drawing shipped with was chosen at a
	// VetoThreshold of 0.605395, and 0.605395/3 = 0.201798 -- the same operating point to
	// within one percent. The derived form REPRODUCES the judgement that was made, in a
	// shape no retrain can invalidate. An operator still overrides it with -near-band;
	// only the default is scale-free.
	defaultVetoNearBand = pagegate.VetoThreshold / 3
	// defaultVetoAcceptedRows, defaultVetoNearRows and defaultVetoDeepRows are the three
	// bands' quotas. They are COUNTS, not shares, because the human confirmation budget
	// is absolute and does not scale with the frame -- which is also why no band may be
	// censused here. Over the CLOSED capture window (18,233 framed pages, a 12,036-row
	// drop set banded 2,025 / 370 / 9,641 -- read against the weights and the 0.20 band
	// edge that shipped BEFORE the 737-row refit, so the band populations have moved
	// even though the frame has not) a census of the accepted band alone would owe
	// 2,025 Blind Confirmations and the drawing 2,145; these defaults draw
	// 100 + 80 + 40 = 220, the order of a pass a person finishes. The quotas are a
	// confirmation budget and do not move with a refit.
	//
	// 100 is what the accepted band's question costs to answer. A 100-row sample of 2,025
	// pins that band's false-drop rate to a standard error of at most ~5 points --
	// sqrt(p(1-p)/100) * sqrt(1925/2024) is 4.9pp at p=0.5 and 2.9pp at p=0.1 -- and that
	// sampling variance is dominated by a bias no quota can remove: which pages land in
	// this band at all is decided by the live extractor's verdict, which runs at 0.454
	// precision against human labels (ADR-0049). Spending the confirmation budget against
	// the smaller error while the larger one stands is not a trade worth making.
	defaultVetoAcceptedRows = 100
	defaultVetoNearRows     = 80
	defaultVetoDeepRows     = 40
)

// boundaryBaselineConfig is TODAY'S blanket accept: the Extract Gate as it behaved
// before ADR-0044's Positive Evidence rung. RequirePositiveEvidence is set FALSE
// explicitly rather than left at its default so this keeps meaning "the previous
// behaviour" after #264 flips that default on.
//
// LearnedVeto is pinned FALSE for the same reason (ADR-0049): the baseline is the
// pre-ADR-0044 gate, which had no rung 9 at all, and a default flip that quietly armed
// one here would make AuditFalseDrops attribute veto-caused drops to the baseline's
// reject rungs.
func boundaryBaselineConfig() crawler.LLMGateConfig {
	cfg := crawler.DefaultLLMGateConfig()
	cfg.RequirePositiveEvidence = false
	cfg.LearnedVeto = false
	return cfg
}

// boundaryCandidateConfig is the tiered Positive Evidence rule as the gate ships it
// TODAY (ADR-0044, internal/pagegate/positive_evidence.go). TRUE is set explicitly
// for the same reason the baseline sets FALSE.
//
// It is no longer the rule that DREW this stratum. The draw was taken against #258's
// rule, and #257 widened that rule to the false-drops the stratum measured, so the
// committed rows are a HISTORICAL disagreement set: 29 of them extract under the rule
// this function now returns. The stratum was kept rather than re-drawn -- re-drawing
// discards the recovered postings, which are the evidence, and owes 188 fresh human
// confirmations -- and TestCommittedBoundaryRecoveryLedger is the ledger of what
// changed. A fresh DRAW (goldset-sample-boundary) still uses this function and still
// gets today's boundary, which is why it reads the shipping rule rather than a pinned
// copy of #258's.
//
// The rule lives HERE, in code, rather than in a -gate-config flag: a flag would let
// a later run silently redefine the boundary, and the drawn rows would then claim a
// boundary nobody could re-derive.
//
// LearnedVeto is pinned FALSE, and that pin is load-bearing beyond the draw (ADR-0049).
// This function is also how the trainer and two guards name "the pages the Positive
// Evidence rung accepts": rung 8's accept population is by definition PRE-veto, since
// the veto only ever prunes it. Left at its default, the day EXTRACT_LEARNED_VETO's
// default flips, scorerSamples would fit its operating point against the veto's own
// survivors, TestCommittedThresholdLosesNoDetailRowThePositiveEvidenceRungAccepts would
// become a tautology, and the subtractive-only guard's OFF arm would be a second copy
// of its ON arm.
func boundaryCandidateConfig() crawler.LLMGateConfig {
	cfg := crawler.DefaultLLMGateConfig()
	cfg.RequirePositiveEvidence = true
	cfg.LearnedVeto = false
	return cfg
}

// vetoBaselineConfig is the Extract Gate exactly as it SHIPS today: every reject
// rung, the Positive Evidence rung on, and the Learned Veto off. It is the veto
// depth's denominator -- "of the pages today's gate extracts" -- and both switches
// are pinned explicitly for the reason the ADR-0044 pair pins them: the day
// EXTRACT_LEARNED_VETO's default flips, a baseline left at the default would
// silently become the POST-veto gate, and the depth would collapse to zero while
// still reporting itself as a measurement.
//
// It returns the same struct boundaryCandidateConfig returns today, and it is
// deliberately NOT aliased to it. The two are separate provenance claims that are
// allowed to diverge: boundaryCandidateConfig is frozen as "the rule ADR-0043's
// committed rows were drawn against", while this one must track whatever production
// ships. Add a rung 10 behind a third switch and the first has to pin it off while
// this one must not.
func vetoBaselineConfig() crawler.LLMGateConfig {
	cfg := crawler.DefaultLLMGateConfig()
	cfg.RequirePositiveEvidence = true
	cfg.LearnedVeto = false
	return cfg
}

// vetoCandidateConfig is what EXTRACT_LEARNED_VETO=true runs, and what
// `score-capture -gate-config <file holding {"LearnedVeto": true}>` scores: the same
// ladder with rung 9 enforcing at the compiled-in VetoThreshold. The flag takes a
// PATH, never inline JSON: loadGateConfig reads the file. Both switches are pinned
// explicitly, for the reason vetoBaselineConfig states -- this config must keep
// meaning "both rungs on" whatever either default later says.
func vetoCandidateConfig() crawler.LLMGateConfig {
	cfg := crawler.DefaultLLMGateConfig()
	cfg.RequirePositiveEvidence = true
	cfg.LearnedVeto = true
	return cfg
}

// boundaryDesign is one boundary drawing's complete definition: the verb that draws
// it, the stratum its rows are stamped with, the two gate configs whose disagreement
// IS the boundary, which half of that disagreement the drawing takes, and HOW it
// selects rows out of that half.
//
// Pair and stratum live in ONE value on purpose. A committed row states which pair
// drew it through its stratum and through nothing else, so a row's provenance is read
// off the artifact rather than remembered; binding the two here makes that true by
// construction rather than by two call sites agreeing to agree.
type boundaryDesign struct {
	// Verb is the llmbench verb that draws it, used to prefix its diagnostics.
	Verb string
	// Stratum stamps every row this design draws. No two designs may share one
	// (TestEachBoundaryDesignStampsItsOwnStratum).
	Stratum goldStratum
	// Selection is how the design turns its half of the disagreement into rows, and it
	// is the second half of a committed row's provenance: because a stratum is claimed
	// by exactly one design, a row's stratum states its inclusion-probability design
	// too. Every design must set it (TestEachBoundaryDesignStampsItsOwnStratum).
	Selection selectionDesign
	// Baseline and Candidate are the pair. They are funcs in THIS FILE rather than a
	// -gate-config flag for the reason boundaryCandidateConfig states: a flag would let
	// a later run silently redefine a boundary that already-committed rows claim, and
	// those rows would then assert a boundary nobody can re-derive.
	Baseline  func() crawler.LLMGateConfig
	Candidate func() crawler.LLMGateConfig
	// ExtractorAcceptsOnly restricts the census to the disagreement's accept half --
	// the pages the LIVE extractor said were one Job Listing. ADR-0043's boundary takes
	// that half because the extractor's accept is its evidence that a dropped page was
	// a real one. The Learned Veto's boundary takes BOTH halves and must: ADR-0049
	// forbids grading this rung against the extractor's verdict at all (precision 0.454
	// against human labels, with its errors concentrated on exactly the pages that
	// decide an operating point), so filtering the drop set by that verdict would
	// import that bias before a human ever reads a row.
	ExtractorAcceptsOnly bool
	// Rule is the one-line statement of what defines this cut, printed in the summary
	// so a run says its own operating point rather than leaving it to be remembered.
	Rule string
	// Floor is a pre-registered condition on the depth, or 0 for a design that has
	// none. It is REPORTED and never moves an exit code, on train-scorer's precedent:
	// merging the tooling is not gated on it, flipping a rung's default is.
	Floor float64
	// Reversal is the diagnostic printed when the candidate config ADDS a page the
	// baseline skips. Each design states its own claim in its own ADR's words.
	Reversal string
}

// positiveEvidenceBoundary is ADR-0043's Boundary Stratum (#263): today's blanket
// accept against the tiered Positive Evidence rule, accept half only.
var positiveEvidenceBoundary = boundaryDesign{
	Verb:                 "goldset-sample-boundary",
	Stratum:              stratumBoundary,
	Selection:            selectionCensus,
	Baseline:             boundaryBaselineConfig,
	Candidate:            boundaryCandidateConfig,
	ExtractorAcceptsOnly: true,
	Rule:                 "the tiered Positive Evidence rule (ADR-0044, internal/pagegate/positive_evidence.go)",
	Reversal: "the rung is supposed to be purely ADDITIVE, so this stratum's one-sided " +
		"definition no longer describes the boundary",
}

// learnedVetoBoundary is ADR-0049's rollout drawing (#304): the shipping gate against
// the same gate with rung 9 armed, BOTH halves of the disagreement, drawn as a
// STRATIFIED SAMPLE of the drop set rather than a census of it.
//
// The census this drawing shipped with does not survive contact with this rung. The
// capture window closed at 18,233 framed pages, and against the shipped weights it holds
// a drop set of 12,036 rows, banded 2,025 accepted / 370 near / 9,641 deep. The
// disagreement is most of the stream here, where ADR-0043's boundary was 188 pages --
// and ADR-0043 requires a HUMAN confirmation on every Boundary Stratum row, so a census
// would put 2,145 rows in front of a labeller, never be finished, and block the refit
// indefinitely. Sampling is what makes the obligation finishable; it does not weaken it.
//
// EVERY band is sampled, the accepted one included. A band's population scales with the
// frame, so a censused band keeps the draw's size a function of the frame's size -- the
// failure the bands exist to fix.
//
// Stratifying on the live verdict is NOT the filtering this ADR forbids. Filtering
// would give the pages the extractor abstained on inclusion probability ZERO, importing
// its 0.454 precision into the sample. Here every page of the drop set keeps a non-zero,
// KNOWN inclusion probability and the weights restore the whole set; no verdict decides
// a label, and ExtractorAcceptsOnly stays false.
var learnedVetoBoundary = boundaryDesign{
	Verb:                 "goldset-sample-veto-boundary",
	Stratum:              stratumVetoBoundary,
	Selection:            selectionStratified,
	Baseline:             vetoBaselineConfig,
	Candidate:            vetoCandidateConfig,
	ExtractorAcceptsOnly: false, // see boundaryDesign.ExtractorAcceptsOnly, and ADR-0049
	Rule: fmt.Sprintf("Posting Score < %.6f (pagegate.VetoThreshold, ADR-0049) -- compiled in "+
		"beside the weights, and it moves with every refit", pagegate.VetoThreshold),
	Floor: vetoFloor, // ADR-0049's pre-registered 10%, the same constant the trainer reports against
	Reversal: "the Learned Veto is SUBTRACTIVE ONLY (ADR-0049): it can withhold a call, never " +
		"add one, so a page it admits means the rung is not the rule this drawing assumes",
}

// boundaryOutcome is one design's config pair replayed over a capture frame: the
// whole answer, read two ways -- as a DEPTH (a label-free number) and as a DROP SET
// (a census to confirm). Both come from one replay so the number an operator decided
// on and the set they then drew can never be two different computations (ADR-0049).
type boundaryOutcome struct {
	// Frame is how many candidates were replayed.
	Frame int
	// BaselineAccepts is how many of them the design's BASELINE extracts: the pages
	// the pair agrees on plus the pages it disagrees on. It is the depth's
	// denominator. The capture tap sits downstream of the Extract Gate, so on a fresh
	// window it should sit within a few rows of Frame; a large gap means a reject rung
	// moved since the window and the frame is stale.
	BaselineAccepts int
	// DroppedAccepted and DroppedAbstained are the disagreement -- baseline extracts,
	// candidate skips -- split by the LIVE extractor's own verdict. The split is
	// REPORTED for both designs and ACTED ON only by a design that says it takes one
	// half.
	DroppedAccepted  []candidate
	DroppedAbstained []candidate
	// Reversed collects any page the CANDIDATE extracts that the baseline skips: the
	// design's own subtractive claim, returned rather than asserted so a rule that
	// stops being subtractive is REPORTED instead of silently halving the boundary.
	Reversed []string
}

// Drop is the size of the whole disagreement, both verdict halves.
func (o boundaryOutcome) Drop() int { return len(o.DroppedAccepted) + len(o.DroppedAbstained) }

// Depth is the share of the baseline's accepts the candidate withholds -- for
// learnedVetoBoundary, the **Veto Depth**. It is 0 when the baseline accepts
// nothing, which the caller refuses before reading it: a depth with no denominator
// is a wrong frame, not a zero.
func (o boundaryOutcome) Depth() float64 {
	if o.BaselineAccepts == 0 {
		return 0
	}
	return float64(o.Drop()) / float64(o.BaselineAccepts)
}

// DropSet is the population the design draws from: both verdict halves, or the accept
// half alone. It is deliberately not called a census -- a census design takes all of
// it, a stratified one samples it (ADR-0049) -- and the result never aliases the
// outcome's own slices.
func (o boundaryOutcome) DropSet(d boundaryDesign) []candidate {
	out := make([]candidate, 0, o.Drop())
	out = append(out, o.DroppedAccepted...)
	if d.ExtractorAcceptsOnly {
		return out
	}
	return append(out, o.DroppedAbstained...)
}

// replayBoundary re-streams the capture and replays the design's BOTH gate configs
// over each candidate's captured Content, counting what the baseline extracts and
// partitioning the pages the two disagree on by the live extractor's own verdict. It
// decodes one record at a time and keeps only the candidate handle, so peak memory
// stays proportional to the disagreement set rather than to the whole capture.
//
// A DISAGREEMENT row also carries away its Posting Score, which is what a stratified
// design bands it on (ADR-0049). It is read here, on the pages that need it, rather
// than over the whole frame: the content is already decoded at this point, and the
// score of a page no drawing will ever look at is work nobody asked for.
func replayBoundary(path string, scan captureScan, d boundaryDesign) (boundaryOutcome, error) {
	byLine := map[int]candidate{}
	for _, c := range scan.Candidates {
		byLine[c.Line] = c
	}

	f, err := os.Open(path)
	if err != nil {
		return boundaryOutcome{}, fmt.Errorf("open capture %q: %w", path, err)
	}
	defer func() { _ = f.Close() }()

	baselineCfg, candidateCfg := d.Baseline(), d.Candidate()
	out := boundaryOutcome{
		Frame:            len(scan.Candidates),
		DroppedAccepted:  []candidate{},
		DroppedAbstained: []candidate{},
		Reversed:         []string{},
	}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), captureScanBuffer)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		cand, ok := byLine[lineNo]
		if !ok {
			continue
		}
		var rec goldRow
		if err := json.Unmarshal(sc.Bytes(), &rec); err != nil {
			return boundaryOutcome{}, fmt.Errorf("capture line %d: %w", lineNo, err)
		}
		u, err := crawler.NewURL(rec.URL)
		if err != nil {
			return boundaryOutcome{}, fmt.Errorf("capture line %d: url %q: %w", lineNo, rec.URL, err)
		}
		before := pagegate.ShouldExtract(u, &rec.Content, baselineCfg)
		after := pagegate.ShouldExtract(u, &rec.Content, candidateCfg)
		if before {
			out.BaselineAccepts++
		}
		switch {
		case before == after:
			continue
		case !before && after:
			out.Reversed = append(out.Reversed, rec.URL)
		case cand.Verdict:
			cand.Score = pagegate.Score(u, &rec.Content)
			out.DroppedAccepted = append(out.DroppedAccepted, cand)
		default:
			cand.Score = pagegate.Score(u, &rec.Content)
			out.DroppedAbstained = append(out.DroppedAbstained, cand)
		}
	}
	if err := sc.Err(); err != nil {
		return boundaryOutcome{}, fmt.Errorf("read capture %q: %w", path, err)
	}
	return out, nil
}

// withStratum rewrites each candidate's stratum to s and orders them by URL. It is
// where censusSelection stamps a drawing's rows, and the only place a boundary row's
// stratum is decided -- which is what makes the stratum a reliable statement about
// which config pair drew the row.
//
// The sort is STABLE for the reason the fit's two sorts are (trainscorerfit.go): the
// URL key is total only by accident -- scanCapture dedupes by URL today -- and the
// drawn rows are appended to the substrate in this order, so leaving two equal rows to
// the sort's internals would make the committed file's byte order depend on the
// toolchain. Determinism is what a drawing's provenance rests on.
func withStratum(cands []candidate, s goldStratum) []candidate {
	out := make([]candidate, 0, len(cands))
	for _, c := range cands {
		c.Stratum = s
		out = append(out, c)
	}
	slices.SortStableFunc(out, func(a, b candidate) int { return strings.Compare(a.URL, b.URL) })
	return out
}

// censusSelection builds a CENSUS drawing's selection by hand: a census has no quota
// to apply and no accept share to weight by. It emits ONE CELL PER VERDICT HALF the
// design takes, both at boundaryCensusWeight -- readSelected keys each row's weight on
// its whole cell, so a design that draws the abstain half without a cell for it would
// write those rows at weight 0 and fail the substrate's weight guard. It leaves the
// cell's band empty, which is what a census's cell IS: it draws every page of the half
// at one probability, so there is no band to distinguish.
func censusSelection(d boundaryDesign, census []candidate) selection {
	byVerdict := map[bool]int{}
	for _, c := range census {
		byVerdict[c.Verdict]++
	}
	verdicts := []bool{true}
	if !d.ExtractorAcceptsOnly {
		verdicts = append(verdicts, false)
	}
	sel := selection{Chosen: withStratum(census, d.Stratum)}
	for _, v := range verdicts {
		sel.Cells = append(sel.Cells, cellResult{
			Key:        cellKey{Stratum: d.Stratum, Verdict: v},
			Population: byVerdict[v],
			Sampled:    byVerdict[v],
			Weight:     boundaryCensusWeight,
		})
	}
	return sel
}

// vetoBandPlan is the operator's half of the stratified design: the score band that
// counts as "just below the cut", and how many rows to draw from each of the three
// bands.
//
// These are FLAGS where the bands themselves are code, for the reason
// boundaryCandidateConfig gives about the pair: what the bands MEAN is the design and
// may not drift, while how many rows a human can confirm this week is not a design
// question at all.
type vetoBandPlan struct {
	// NearBand is the score width below pagegate.VetoThreshold that counts as "near":
	// the near band is [VetoThreshold-NearBand, VetoThreshold) and everything below it
	// is the deep band.
	NearBand float64
	// AcceptedRows, NearRows and DeepRows are the three bands' quotas, in boundaryBands
	// order. 0 means take the whole band, takeByHash's own convention -- which on the
	// accepted band is also the exact way back to the census this drawing shipped with.
	AcceptedRows, NearRows, DeepRows int
}

// validate refuses a plan that would degenerate the design before anything is read.
// Both refusals are about a band that cannot exist: a band edge outside the score's
// own range leaves one of the three cells empty by construction, and a negative quota
// would slip through takeByHash's "n <= 0 takes everything" convention as a census.
func (p vetoBandPlan) validate() error {
	if p.NearBand <= 0 || p.NearBand >= pagegate.VetoThreshold {
		return fmt.Errorf("-near-band must be in (0, %.6f) -- the compiled pagegate.VetoThreshold -- got %g; "+
			"outside it one of the three bands is empty by construction and the design degenerates", pagegate.VetoThreshold, p.NearBand)
	}
	if p.AcceptedRows < 0 || p.NearRows < 0 || p.DeepRows < 0 {
		return fmt.Errorf("-accepted-rows, -near-rows and -deep-rows must be >= 0 (0 takes the whole band), got %d, %d and %d; "+
			"a negative quota would silently become a census", p.AcceptedRows, p.NearRows, p.DeepRows)
	}
	return nil
}

// bandOf places an ABSTAINED page in one of the two score bands. The accept half is
// bandAccepted by its live verdict and NEVER by its score, because what makes those
// pages one cell is that the extractor read each of them as one posting.
//
// That rule is also what makes the accepted band's own sample uniform IN SCORE: it is
// one cell drawn at one probability across the whole 0..VetoThreshold spread, so every
// score region is represented at the same rate and a later score-conditioned read of
// that band is itself a simple random sample of its own sub-population, carrying the
// one band weight. Sub-banding it by score would buy a little variance and cost that.
func bandOf(score, threshold, nearBand float64) goldBand {
	if score >= threshold-nearBand {
		return bandNear
	}
	return bandDeep
}

// bandDropSet partitions a drop set into the three bands and stamps each candidate
// with the band it landed in. The three partition the set exactly, so no page can be
// selected twice and none can be missed.
//
// A page scoring at or above pagegate.VetoThreshold in a drop set is REFUSED rather
// than banded: the drop set holding a page the veto keeps means the pair replayed was
// not the Learned Veto's, and stamping such a page with a band would be a claim about
// a cut it is on the other side of.
func bandDropSet(drawable []candidate, p vetoBandPlan) (map[goldBand][]candidate, error) {
	out := map[goldBand][]candidate{}
	for _, b := range boundaryBands {
		out[b] = []candidate{}
	}
	for _, c := range drawable {
		if c.Score >= pagegate.VetoThreshold {
			return nil, fmt.Errorf("%s is in the drop set yet scores %.6f, at or above pagegate.VetoThreshold %.6f: "+
				"this pair is not the Learned Veto's, so banding it on the Posting Score would stamp a band that is a lie",
				c.URL, c.Score, pagegate.VetoThreshold)
		}
		b := bandAccepted
		if !c.Verdict {
			b = bandOf(c.Score, pagegate.VetoThreshold, p.NearBand)
		}
		c.Band = b
		out[b] = append(out[b], c)
	}
	return out, nil
}

// stratifiedSelection draws the design's sample: it bands the drop set, takes each
// band's quota in deterministic hash order, and weights every row by the INVERSE of
// its selection probability, normalized within this drawing:
//
//	w_c = (N_c / n_c) * (n / N)
//
// so the drawn weights sum to n and the per-drawing balance weightsBalanced asserts
// holds by construction, exactly as it does for the random drawing.
//
// It deliberately does NOT go through weightsFor. That function reconstructs a VERDICT
// share from the capture's per-verdict caps, because the random drawing's frame is a
// capped stream sample with unobserved stream behind it. This drawing's population is
// ENUMERATED by the replay: the caps do not distort it, the inclusion probabilities are
// known exactly, and dragging an accept-share estimate in would add an estimate the
// design neither needs nor can use.
//
// What the resulting weights estimate is stated once, here, because it is the thing a
// later reader will get wrong: the pages the Learned Veto would withhold the call from
// over THIS capture frame, minus the URLs earlier drawings already committed. It is not
// a stream estimate -- a drop set is not a stream -- and these rows must never enter
// bench.ScoreExtractStream.
func stratifiedSelection(d boundaryDesign, drawable []candidate, p vetoBandPlan, seed string) (selection, error) {
	bands, err := bandDropSet(drawable, p)
	if err != nil {
		return selection{}, err
	}
	// All three quotas come from the plan, and 0 takes the band whole (takeByHash's
	// convention). A fully-taken band lands on N_c/n_c == 1 and therefore on exactly the
	// weight a census produces, so the arithmetic below is ONE path for all three bands --
	// and always was: none of it ever depended on the accepted band being taken whole.
	quotas := map[goldBand]int{bandAccepted: p.AcceptedRows, bandNear: p.NearRows, bandDeep: p.DeepRows}

	taken := map[goldBand][]candidate{}
	population, sampled := 0, 0
	for _, b := range boundaryBands {
		taken[b] = takeByHash(bands[b], seed, quotas[b])
		population += len(bands[b])
		sampled += len(taken[b])
	}
	if sampled == 0 {
		return selection{}, fmt.Errorf("the quotas draw no row at all from a %d-page drop set; there is nothing to weight", population)
	}

	sel := selection{}
	chosen := []candidate{}
	for _, b := range boundaryBands {
		n := len(taken[b])
		weight := 0.0
		if n > 0 {
			weight = (float64(len(bands[b])) / float64(n)) * (float64(sampled) / float64(population))
		}
		// An empty band still emits its cell, so a band the frame simply has no pages in
		// is VISIBLE in the account rather than absent from it.
		sel.Cells = append(sel.Cells, cellResult{
			Key:        cellKey{Stratum: d.Stratum, Verdict: b == bandAccepted, Band: b},
			Population: len(bands[b]),
			Sampled:    n,
			Weight:     weight,
		})
		chosen = append(chosen, taken[b]...)
	}
	sel.Chosen = withStratum(chosen, d.Stratum)
	return sel, nil
}

// boundaryDrawArgs is one boundary run's inputs, parsed and validated.
type boundaryDrawArgs struct {
	Design  boundaryDesign
	Capture string
	Dir     string
	Since   time.Time
	// Plan and Seed are the STRATIFIED design's inputs and are ignored by a census
	// one. Seed keys the within-band selection, so the same capture and seed always
	// yield a byte-identical file while a new seed is a genuine unbiased resample.
	Plan vetoBandPlan
	Seed string
	// Draw appends the drawing to the Extract Gold Set. False reports the depth and
	// writes nothing -- and never even opens Dir.
	Draw bool
}

// runBoundaryDrawing is the body BOTH boundary verbs run: it scans the capture,
// narrows it to the faithful frame at or after Since, replays the design's pair over
// every candidate in that frame, and either reports the reading or appends the drop
// set to the Extract Gold Set. Like goldset-sample-random the draw is APPEND-ONLY:
// existing labels, provenance and expected extractions pass through untouched.
//
// The exclusion of already-committed URLs happens AFTER the replay, on the drop set
// alone. A page cannot carry two drawings' weights, so it must not be DRAWN twice --
// but excluding it before the replay would make the depth a number about how much of
// this frame an earlier drawing happened to sample, and the depth is ADR-0049's
// pre-registered go/no-go over the frame as a whole. For a stratified design the
// exclusion therefore narrows the SAMPLING POPULATION, which is what makes each band's
// inclusion probability correct: what it samples is "the drop set minus the pages
// earlier drawings hold", exactly as the #263 drawing defined its own frame. The depth
// is still over the whole frame, and both numbers are reported.
//
// Returns the process exit code: 2 on a usage or validation error, 1 on IO, 0
// otherwise. Nothing is written unless every check passes.
func runBoundaryDrawing(a boundaryDrawArgs, w io.Writer) int {
	d := a.Design
	if d.Selection == selectionStratified {
		if err := a.Plan.validate(); err != nil {
			fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
			return 2
		}
	}
	scan, err := scanCapture(a.Capture)
	if err != nil {
		fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
		return 1
	}
	framed, outOfFrame := frameSince(scan, a.Since)

	outcome, err := replayBoundary(a.Capture, framed, d)
	if err != nil {
		fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
		return 1
	}
	if len(outcome.Reversed) > 0 {
		fmt.Fprintf(os.Stderr, "llmbench %s: %d pages are extracted by the candidate rule and skipped by the baseline (e.g. %s).\n",
			d.Verb, len(outcome.Reversed), outcome.Reversed[0])
		fmt.Fprintf(os.Stderr, "  %s. Nothing was written.\n", d.Reversal)
		return 2
	}
	if outcome.BaselineAccepts == 0 {
		fmt.Fprintf(os.Stderr, "llmbench %s: the baseline rule extracts nothing in this frame, so the depth has no denominator. Check -capture and -since.\n", d.Verb)
		return 2
	}

	summary := boundarySummary{
		Design:     d,
		Scan:       scan,
		Outcome:    outcome,
		OutOfFrame: outOfFrame,
		Plan:       a.Plan,
	}
	// Report mode stops here, before the substrate is even opened. It is the
	// non-destructive default for the veto's drawing because the depth is ADR-0049's
	// pre-registered go/no-go: writing the rows it implies before the operator has read
	// the number would change the fitted weights and owe a human confirmation per row,
	// on a rollout the number may yet say no to. An EMPTY drop set is not an error
	// here -- "the candidate would withhold nothing" is a measurement.
	if !a.Draw {
		// A stratified design also previews its PLAN here -- per band, the population and
		// the rows the current quotas would take -- because that is what the operator
		// tunes the flags from. Those populations are PRE-exclusion by construction: this
		// path never opens the substrate, and it must not start.
		if d.Selection == selectionStratified {
			bands, err := bandDropSet(outcome.DropSet(d), a.Plan)
			if err != nil {
				fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
				return 2
			}
			summary.Bands = bands
		}
		printBoundarySummary(w, summary)
		return 0
	}

	// The substrate MUST already exist, for the same reason the random drawing
	// requires one: this stratum extends the committed file, and silently starting a
	// new one would strand every existing label.
	substrate, _ := goldSetPaths(a.Dir)
	existing, err := readGoldSet(substrate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "llmbench %s: %v (this stratum extends an existing gold set; run goldset-sample first)\n", d.Verb, err)
		return 1
	}
	committed := map[string]struct{}{}
	for _, row := range existing {
		committed[row.URL] = struct{}{}
	}
	// A STRATIFIED drawing is drawn ONCE. A census tolerates a repeat, because a page
	// taken under it had inclusion probability 1 whenever it was taken; a sample does
	// not, and a second window's rows would carry a second set of inclusion
	// probabilities into one stratum. No half of THIS drawing is repeat-tolerant any
	// more -- the accepted band is sampled too -- so this refusal carries the whole
	// guarantee rather than most of it.
	if d.Selection == selectionStratified {
		for _, row := range existing {
			if row.Stratum != d.Stratum {
				continue
			}
			fmt.Fprintf(os.Stderr, "llmbench %s: the substrate already holds %s rows (e.g. %s), and a stratified drawing is drawn ONCE.\n",
				d.Verb, d.Stratum, row.URL)
			fmt.Fprintf(os.Stderr, "  Appending a second window's sample would pool two selection designs in one stratum, "+
				"which is exactly what makes a weighted estimate over it unrecoverable. A fresh window is a new DRAWING: "+
				"declare it in code, as every drawing before it was. Nothing was written.\n")
			return 2
		}
	}
	dropSet := outcome.DropSet(d)
	drawable, alreadyCommitted := withoutURLs(dropSet, committed)
	if len(drawable) == 0 {
		if len(dropSet) == 0 {
			fmt.Fprintf(os.Stderr, "llmbench %s: the two configs disagree on no page this drawing takes; there is no boundary to draw\n", d.Verb)
		} else {
			fmt.Fprintf(os.Stderr, "llmbench %s: every page on the boundary is already in the substrate; nothing left to draw\n", d.Verb)
		}
		return 2
	}

	sel := censusSelection(d, drawable)
	if d.Selection == selectionStratified {
		sel, err = stratifiedSelection(d, drawable, a.Plan, a.Seed)
		if err != nil {
			fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
			return 2
		}
	}
	drawn, err := readSelected(a.Capture, sel)
	if err != nil {
		fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
		return 1
	}
	if err := validateDrawnBoundaryRows(d, sel, drawn, committed); err != nil {
		fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
		return 2
	}

	merged := append(append([]goldRow{}, existing...), drawn...)
	if err := writeGoldSetFiles(a.Dir, merged); err != nil {
		fmt.Fprintf(os.Stderr, "llmbench %s: %v\n", d.Verb, err)
		return 1
	}

	summary.Sel, summary.Drawn, summary.Merged = sel, drawn, merged
	summary.AlreadyCommitted, summary.Substrate, summary.Drew = alreadyCommitted, substrate, true
	printBoundarySummary(w, summary)
	return 0
}

// validateDrawnBoundaryRows refuses a draw that could corrupt the substrate: a row
// already committed (one page cannot carry two drawings' incompatible weights), a
// duplicate within the draw, a row outside the design's own stratum, a weight the
// design's own selection cannot have produced, or a row that arrived carrying a label.
// Nothing is written until it passes, so a bad draw leaves the committed file exactly
// as it was.
//
// The weight check is the design's, because the two designs mean different things by a
// legitimate weight: a census row is exactly boundaryCensusWeight, while a stratified
// row must carry one of the SAMPLED cells' weights and the draw as a whole must
// normalize to its own row count. That pair is the direct regression test for a
// cell-keying bug -- the hazard censusSelection's two-cell comment already names, one
// band deeper.
//
// The live verdict is checked only for a design that says it takes the accept half.
// The Learned Veto's drawing takes both halves and MUST NOT be given this check back:
// ADR-0049 forbids grading that rung against the extractor's own verdict, so a drop
// set filtered by it would import that bias before a human ever reads a row.
func validateDrawnBoundaryRows(d boundaryDesign, sel selection, drawn []goldRow, committed map[string]struct{}) error {
	drawnWeights := map[float64]struct{}{}
	for _, c := range sel.Cells {
		if c.Sampled > 0 && c.Weight > 0 {
			drawnWeights[c.Weight] = struct{}{}
		}
	}
	seen := map[string]struct{}{}
	for _, row := range drawn {
		if _, dup := committed[row.URL]; dup {
			return fmt.Errorf("drew %q, which the substrate already carries", row.URL)
		}
		if _, dup := seen[row.URL]; dup {
			return fmt.Errorf("drew %q twice", row.URL)
		}
		seen[row.URL] = struct{}{}
		if row.Stratum != d.Stratum {
			return fmt.Errorf("drew %q in stratum %q, want %q", row.URL, row.Stratum, d.Stratum)
		}
		switch d.Selection {
		case selectionStratified:
			if row.Weight <= 0 {
				return fmt.Errorf("drew %q with weight %g; a stratified drawing weights every row by the inverse of its "+
					"selection probability, and a non-positive weight means its cell was keyed wrong", row.URL, row.Weight)
			}
			if _, ok := drawnWeights[row.Weight]; !ok {
				return fmt.Errorf("drew %q with weight %g, which is no sampled cell's weight; its cell was keyed wrong", row.URL, row.Weight)
			}
		default:
			if row.Weight != boundaryCensusWeight {
				return fmt.Errorf("drew %q with weight %g, want the census weight %g", row.URL, row.Weight, boundaryCensusWeight)
			}
		}
		if d.ExtractorAcceptsOnly && !row.Verdict {
			return fmt.Errorf("drew %q, whose live verdict was abstain; this drawing takes the accept half of the disagreement", row.URL)
		}
		if row.Label != "" {
			return fmt.Errorf("drew %q carrying label %q; a fresh draw is unlabelled", row.URL, row.Label)
		}
	}
	if d.Selection == selectionStratified && len(drawn) > 0 && !weightsBalanced(drawn, 1e-9) {
		return fmt.Errorf("the drawn rows' weights sum to %.9f over %d rows; a drawing's weights normalize to its own row count",
			weightSum(drawn), len(drawn))
	}
	return nil
}

// boundarySummary is everything the account of one boundary run reads from. The
// fields below Outcome are filled only by a run that actually drew.
type boundarySummary struct {
	Design boundaryDesign
	// Scan is the capture BEFORE framing, so the report can account for what each
	// narrowing step dropped. The framed count is Outcome.Frame -- one number, read off
	// the replay that actually used it.
	Scan       captureScan
	Outcome    boundaryOutcome
	OutOfFrame int

	// Plan and Bands are a STRATIFIED design's half of the account. Bands is filled in
	// REPORT mode only, where it is the plan preview the flags are tuned from, and its
	// populations are therefore PRE-exclusion: that path never opens the substrate.
	Plan  vetoBandPlan
	Bands map[goldBand][]candidate

	// Sel is the selection a draw actually realized: per cell, the population it drew
	// from, the rows it took, and the weight they carry.
	Sel              selection
	Drawn, Merged    []goldRow
	AlreadyCommitted int
	Substrate        string
	Drew             bool
}

// bandNote states in one line what a band is for, so the report argues its own design
// rather than leaving the reader to remember it.
func bandNote(b goldBand, p vetoBandPlan) string {
	switch b {
	case bandAccepted:
		return "the live-accept half: the candidate false-drops, and what the recall claim is read on"
	case bandNear:
		return fmt.Sprintf("score in [%.6f, %.6f) -- where the threshold is decided", pagegate.VetoThreshold-p.NearBand, pagegate.VetoThreshold)
	case bandDeep:
		return fmt.Sprintf("score < %.6f -- is the bottom really junk?", pagegate.VetoThreshold-p.NearBand)
	default:
		return ""
	}
}

// bandScoreRange renders a band's observed Posting Score range, or a marker for an
// empty band -- an empty band is a fact about the frame, not a gap in the report.
func bandScoreRange(cands []candidate) string {
	if len(cands) == 0 {
		return "(empty)"
	}
	lo, hi := cands[0].Score, cands[0].Score
	for _, c := range cands[1:] {
		lo, hi = min(lo, c.Score), max(hi, c.Score)
	}
	return fmt.Sprintf("score %.6f..%.6f", lo, hi)
}

// printBoundarySummary writes the account an operator needs to trust a boundary run:
// what the capture held, what each narrowing step dropped, the rule the cut was taken
// at, the depth and its denominator, BOTH halves of the disagreement, and the
// reversed count that proves the candidate subtractive. A run that drew adds the two
// row counts and its realized per-cell design; a run that only reported says so, names
// the flag that would draw, and -- for a stratified design -- previews the plan the
// flags currently describe.
//
// There is deliberately NO accept share, for either design. A census describes no
// stream to weight toward, and a stratified drawing's population is ENUMERATED by the
// replay rather than sampled out of a capped stream, so there is no cap correction to
// apply either. Printing one would invite somebody to weight this drawing toward a
// population it is not about.
func printBoundarySummary(w io.Writer, s boundarySummary) {
	o, d := s.Outcome, s.Design
	half := "both halves"
	if d.ExtractorAcceptsOnly {
		half = "the accept half"
	}
	fmt.Fprintf(w, "extract gold set %s stratum\n", d.Stratum)
	fmt.Fprintf(w, "  capture lines        %d\n", s.Scan.Lines)
	fmt.Fprintf(w, "  duplicate lines      %d (deduped by url, latest ts wins)\n", s.Scan.Duplicates)
	fmt.Fprintf(w, "  dropped oversized    %d (raw line > %d bytes)\n", s.Scan.Oversized, maxCandidateBytes)
	fmt.Fprintf(w, "  dropped bad url      %d\n", s.Scan.BadURL)
	fmt.Fprintf(w, "  dropped out-of-frame %d (superseded parser, or an unparseable ts)\n", s.OutOfFrame)
	fmt.Fprintf(w, "  candidate frame      %d\n", o.Frame)
	fmt.Fprintf(w, "  rule                 %s\n", d.Rule)
	fmt.Fprintf(w, "  gate extracts        %d of %d framed (the depth's denominator: what the baseline rule extracts)\n", o.BaselineAccepts, o.Frame)
	fmt.Fprintf(w, "  drop set             %d (live accept %d / live abstain %d; this drawing takes %s)\n",
		o.Drop(), len(o.DroppedAccepted), len(o.DroppedAbstained), half)
	fmt.Fprintf(w, "  depth                %.4f%s\n", o.Depth(), floorVerdict(d, o))
	if d.Floor > 0 {
		// The pre-registered condition has a second half -- losing none of the rung's
		// detail rows -- which is in-sample and cannot be read off an unlabelled frame.
		// Saying so here is what keeps a MET verdict from being read as the whole
		// condition.
		fmt.Fprintf(w, "                       this is the depth half of the condition only; the zero-detail-loss half is\n")
		fmt.Fprintf(w, "                       in-sample and is re-checked after the refit (step 4 of the rollout)\n")
	}
	fmt.Fprintf(w, "  reversed             %d (pages the CANDIDATE adds; this pair's candidate can only ever subtract, so this must be 0)\n", len(o.Reversed))
	if !s.Drew {
		if d.Selection != selectionStratified {
			fmt.Fprintf(w, "  wrote                nothing. Re-run with -draw to append the %d-row census.\n", len(o.DropSet(d)))
			return
		}
		would := 0
		quotas := map[goldBand]int{bandAccepted: s.Plan.AcceptedRows, bandNear: s.Plan.NearRows, bandDeep: s.Plan.DeepRows}
		for _, b := range boundaryBands {
			take := len(s.Bands[b])
			if q := quotas[b]; q > 0 && q < take {
				take = q
			}
			would += take
			quota := "census"
			if q := quotas[b]; q > 0 {
				quota = fmt.Sprint(q)
			}
			fmt.Fprintf(w, "  %-21s population %5d  quota %-6s would draw %5d  %s\n",
				"band "+string(b), len(s.Bands[b]), quota, take, bandNote(b, s.Plan))
			fmt.Fprintf(w, "                       %s\n", bandScoreRange(s.Bands[b]))
		}
		fmt.Fprintf(w, "                       these populations are PRE-exclusion: this mode never opens the gold set,\n")
		fmt.Fprintf(w, "                       so the pages earlier drawings already hold are still counted here\n")
		fmt.Fprintf(w, "  wrote                nothing. Re-run with -draw to sample %d rows from the %d-page drop set.\n", would, len(o.DropSet(d)))
		return
	}
	fmt.Fprintf(w, "  dropped committed    %d (boundary pages the substrate already carries)\n", s.AlreadyCommitted)
	if d.Selection == selectionStratified {
		for _, c := range s.Sel.Cells {
			fmt.Fprintf(w, "  %-21s verdict=%-5v population %5d  sampled %3d  weight %.5f\n",
				"cell "+string(c.Key.Band), c.Key.Verdict, c.Population, c.Sampled, c.Weight)
		}
	}
	fmt.Fprintf(w, "  drawn rows           %d\n", len(s.Drawn))
	if d.Selection == selectionStratified {
		fmt.Fprintf(w, "  drawn weight sum     %.4f (inverse selection probability, normalized to the drawn rows)\n", weightSum(s.Drawn))
	} else {
		fmt.Fprintf(w, "  drawn weight sum     %.4f (census: every weight is exactly %g)\n", weightSum(s.Drawn), boundaryCensusWeight)
	}
	fmt.Fprintf(w, "  substrate rows       %d (%d existing + %d drawn)\n", len(s.Merged), len(s.Merged)-len(s.Drawn), len(s.Drawn))
	if info, err := os.Stat(s.Substrate); err == nil {
		fmt.Fprintf(w, "  wrote                %s (%d bytes)\n", s.Substrate, info.Size())
	}
}

// floorVerdict renders a design's pre-registered condition on the depth, or "" for a
// design that has none. A NOT-MET verdict prints in red and does NOT move the exit
// code: train-scorer's precedent for vetoFloor -- merging the tooling is not gated on
// the condition, flipping the rung's default is.
func floorVerdict(d boundaryDesign, o boundaryOutcome) string {
	if d.Floor <= 0 {
		return ""
	}
	if o.Depth() < d.Floor {
		return red(fmt.Sprintf("   FLOOR NOT MET (>= %.4f of the baseline's accepts, ADR-0049): "+
			"the honest outcome is an amendment to ADR-0049 and the rung stays off", d.Floor))
	}
	return fmt.Sprintf("   FLOOR MET (>= %.4f of the baseline's accepts, ADR-0049)", d.Floor)
}

// runGoldSetSampleBoundary draws the ADR-0043 BOUNDARY Stratum (#263) and APPENDS
// it to the existing Extract Gold Set: it replays today's blanket accept and the
// tiered Positive Evidence rule over the faithful frame at or after -since and takes
// every page the two disagree on that the LIVE extractor accepted.
//
// It takes NO -gate-config and NO -seed, for the reason boundaryCandidateConfig
// states, and the drawing is a CENSUS of the disagreement's accept half, so there is
// no within-cell order to seed and every weight is exactly 1. That is this drawing's
// property alone: the Learned Veto's drawing samples, and therefore does take a seed.
//
// It also has no -draw: this stratum is drawn and FROZEN (ADR-0043's consequence on
// re-drawing, TestCommittedBoundaryRecoveryLedger), so a report-only mode over it
// would measure a boundary nobody is going to take. Returns the process exit code:
// 2 on a usage or validation error, 1 on IO, 0 on success.
func runGoldSetSampleBoundary(args []string) int {
	fs := flag.NewFlagSet("goldset-sample-boundary", flag.ExitOnError)
	capture := fs.String("capture", "", "extract-capture JSONL written by the EXTRACT_CAPTURE_PATH tap (required; gitignored, never committed)")
	dir := fs.String("dir", defaultGoldSetDir, "directory holding the Extract Gold Set the boundary stratum is appended to")
	since := fs.String("since", "", "RFC3339 cutoff: only capture records at or after it are drawn from (required; excludes windows parsed by a superseded parser)")
	_ = fs.Parse(args)

	if *capture == "" || *since == "" {
		fmt.Fprintln(os.Stderr, "usage: llmbench goldset-sample-boundary -capture <capture.jsonl> -since <RFC3339> [-dir d]")
		return 2
	}
	cutoff, err := time.Parse(time.RFC3339, *since)
	if err != nil {
		fmt.Fprintf(os.Stderr, "llmbench goldset-sample-boundary: -since %q: %v\n", *since, err)
		return 2
	}
	return runBoundaryDrawing(boundaryDrawArgs{
		Design:  positiveEvidenceBoundary,
		Capture: *capture,
		Dir:     *dir,
		Since:   cutoff,
		Draw:    true,
	}, os.Stdout)
}

// runGoldSetSampleVetoBoundary is ADR-0049's rollout reading (#304), and the same
// drawing against the Learned Veto's own pair: the shipping gate with rung 9 off
// versus on. By default it only REPORTS the **veto depth** over the capture frame --
// of the pages today's gate extracts, the share the veto would withhold -- which
// needs no labels and is the pre-registered go/no-go for turning the rung on. Report
// mode also previews the sampling plan the flags below currently describe, which is
// what those flags are tuned from before anything is committed.
//
// -draw appends a STRATIFIED SAMPLE of the pages below the cut as the veto-boundary
// stratum, BOTH halves of the disagreement, because ADR-0049 forbids filtering them by
// the extractor's own verdict. It is a sample rather than a census because the drop set
// is most of the stream on this rung and ADR-0043 requires a human confirmation on every
// Boundary Stratum row: the defaults draw 220 rows where a census of the closed window
// would owe 2,145 and grow with the frame.
//
// EVERY band carries a quota, the accepted one included. It was specified as a census on
// the reasoning that those pages are the candidate false-drops the recall claim is read
// on -- but the band scales with the frame like any other, and the closed window put
// 2,025 rows in it, so a censused band still made the draw's size a function of the
// frame's. That is the very failure the bands were introduced to fix, surviving in the
// one band exempted from them. -accepted-rows 0 restores the census exactly.
//
// Returns the process exit code: 2 on a usage or validation error, 1 on IO, 0 on success.
func runGoldSetSampleVetoBoundary(args []string) int {
	fs := flag.NewFlagSet("goldset-sample-veto-boundary", flag.ExitOnError)
	capture := fs.String("capture", "", "extract-capture JSONL written by the EXTRACT_CAPTURE_PATH tap (required; gitignored, never committed)")
	dir := fs.String("dir", defaultGoldSetDir, "directory holding the Extract Gold Set the veto-boundary stratum is appended to (read only under -draw)")
	since := fs.String("since", "", "RFC3339 cutoff: only capture records at or after it are drawn from (required; excludes windows parsed by a superseded parser)")
	// The default is deliberately NON-destructive, where the two sibling drawing verbs
	// always write: the depth is ADR-0049's pre-registered go/no-go for the whole
	// rollout and must be read before the set it implies is committed, since those rows
	// change the fitted weights and each one owes a human confirmation.
	draw := fs.Bool("draw", false, "append a stratified sample of the drop set to the Extract Gold Set as the veto-boundary stratum; the default reports the veto depth and writes nothing")
	nearBand := fs.Float64("near-band", defaultVetoNearBand, "score width below pagegate.VetoThreshold that counts as JUST BELOW THE CUT: the near band is [VetoThreshold-band, VetoThreshold) and everything below it is the deep band; must be in (0, VetoThreshold)")
	acceptedRows := fs.Int("accepted-rows", defaultVetoAcceptedRows, "rows to draw from the live-accept half of the drop set -- the candidate false-drops the recall claim is read on; 0 takes the whole band")
	nearRows := fs.Int("near-rows", defaultVetoNearRows, "rows to draw from the near band, where the threshold is actually decided; 0 takes the whole band")
	deepRows := fs.Int("deep-rows", defaultVetoDeepRows, "rows to draw from the deep-reject band -- smaller, because this band confirms the bottom is junk and looks for another short posting publishing no structured data (ADR-0049); 0 takes the whole band")
	seed := fs.String("seed", defaultVetoBoundarySeed, "seed for the deterministic within-band selection; changing it is a deliberate resample")
	_ = fs.Parse(args)

	if *capture == "" || *since == "" {
		fmt.Fprintln(os.Stderr, "usage: llmbench goldset-sample-veto-boundary -capture <capture.jsonl> -since <RFC3339> [-dir d] [-draw] [-near-band f] [-accepted-rows n] [-near-rows n] [-deep-rows n] [-seed s]")
		return 2
	}
	cutoff, err := time.Parse(time.RFC3339, *since)
	if err != nil {
		fmt.Fprintf(os.Stderr, "llmbench goldset-sample-veto-boundary: -since %q: %v\n", *since, err)
		return 2
	}
	return runBoundaryDrawing(boundaryDrawArgs{
		Design:  learnedVetoBoundary,
		Capture: *capture,
		Dir:     *dir,
		Since:   cutoff,
		Plan:    vetoBandPlan{NearBand: *nearBand, AcceptedRows: *acceptedRows, NearRows: *nearRows, DeepRows: *deepRows},
		Seed:    *seed,
		Draw:    *draw,
	}, os.Stdout)
}

// boundaryRowsOf projects the replayed capture rows of the Boundary Stratum onto
// what ScoreExtractBoundary folds, carrying each row's confirmation state.
func boundaryRowsOf(rows []captureRow) []bench.BoundaryRow {
	out := []bench.BoundaryRow{}
	for _, row := range rows {
		if row.Stratum != stratumBoundary {
			continue
		}
		out = append(out, bench.BoundaryRow{ExtractVerdictRow: row.ExtractVerdictRow, Confirmed: row.Confirmed})
	}
	return out
}

const (
	// confirmHeadRunes and confirmMidRunes are the two page-text windows the
	// confirmation sheet shows. They are wider than the labeler's worksheet: the
	// confirmer is settling a label somebody else proposed, and a posting's role body
	// often starts below the first screen of a German page.
	confirmHeadRunes = 2000
	confirmMidRunes  = 1200
	// confirmRowsPerFile is the default chunk size. The confirmation is a human pass
	// over ~190 rows; chunking it is what makes a PARTIAL pass legitimate and visible
	// rather than an abandoned one.
	confirmRowsPerFile = 20
)

// confirmChunk is one rendered chunk of the confirmation sheet: its file name, its
// Markdown body, and the row ids it covers, so the caller can write the matching
// id file the human edits down to what they actually read.
type confirmChunk struct {
	Name string
	Body []byte
	IDs  []string
}

// renderConfirmSheet renders rows as ordered Markdown chunks of at most perFile
// rows each. Ordering is by row id: stable, quotable, and independent of the
// proposed label, so the sheet's order can never group the rows by the answer.
//
// Every JSON-LD-derived field, the live extractor's verdict and the gate's own
// marks are WITHHELD -- the same discipline the labeler's worksheet keeps, for a
// sharper reason. The confirmer answers one question, "is this page one Job
// Listing?", and the number the whole stratum exists to produce is what the gate
// concluded about these very pages; showing them that conclusion would anchor the
// answer the rule is being judged against. labels.tsv still carries the verdict:
// that is the REVIEW surface, read after the label exists.
func renderConfirmSheet(rows []goldRow, perFile int) []confirmChunk {
	if perFile <= 0 {
		perFile = confirmRowsPerFile
	}
	ordered := make([]goldRow, len(rows))
	copy(ordered, rows)
	sort.Slice(ordered, func(i, j int) bool { return rowID(ordered[i].URL) < rowID(ordered[j].URL) })

	chunks := []confirmChunk{}
	total := (len(ordered) + perFile - 1) / perFile
	for i := 0; i < len(ordered); i += perFile {
		end := min(i+perFile, len(ordered))
		index := len(chunks) + 1
		chunk := confirmChunk{Name: fmt.Sprintf("confirm-%02d.md", index)}
		var b strings.Builder
		fmt.Fprintf(&b, "# Boundary Stratum confirmation %d/%d\n\n", index, total)
		// The question and the rubric come from the shared value goldset-ui also
		// renders, so the two review surfaces can never put different definitions to
		// the same human (#286).
		fmt.Fprintf(&b, "One question per row: **%s**\n\n", extractLabelQuestion)
		for _, e := range extractLabelRubric {
			fmt.Fprintf(&b, "- `%s` -- %s\n", e.Label, e.Text)
		}
		b.WriteString("\n")
		b.WriteString("The proposed label is an LLM's. Disagreeing with it is the point of this pass.\n\n")
		for _, row := range ordered[i:end] {
			c := confirmViewOf(row)
			chunk.IDs = append(chunk.IDs, c.ID)
			fmt.Fprintf(&b, "---\n\n## %s\n\n", c.ID)
			fmt.Fprintf(&b, "- url: <%s>\n", c.URL)
			fmt.Fprintf(&b, "- proposed: **%s** -- %s\n", c.Label, orNone(c.Note))
			fmt.Fprintf(&b, "- proposed by: %s\n", orNone(c.ProposedBy))
			fmt.Fprintf(&b, "- page title: %s\n", orNone(c.Title))
			fmt.Fprintf(&b, "- outbound links: %d total, %d same-host, %d job-like\n\n", c.URLsTotal, c.URLsSameHost, c.URLsJoblike)
			fmt.Fprintf(&b, "head:\n\n```\n%s\n```\n\n", orNone(c.Head))
			if c.Mid != "" {
				fmt.Fprintf(&b, "mid:\n\n```\n%s\n```\n\n", c.Mid)
			}
		}
		b.WriteString("---\n\nWhen every row above is read, write the ids you confirm to a file and run:\n\n")
		b.WriteString("```sh\n")
		fmt.Fprintf(&b, "printf '%%s\\n' %s > confirmed-%02d.txt\n", strings.Join(chunk.IDs, " "), index)
		fmt.Fprintf(&b, "go run ./cmd/llmbench goldset-apply -confirmed-by \"<your name>\" -confirm-ids confirmed-%02d.txt\n", index)
		b.WriteString("```\n\n")
		b.WriteString("A row whose label you want CHANGED does not belong in that file: edit its `label` column in\n")
		b.WriteString("`cmd/llmbench/extract-goldset/labels.tsv` first (which retracts any confirmation on it), run\n")
		b.WriteString("`goldset-apply`, then confirm it in the next pass.\n")
		chunk.Body = []byte(b.String())
		chunks = append(chunks, chunk)
	}
	return chunks
}

// confirmView is one row as the confirmer reads it: what the page itself says plus
// the label somebody proposed for it, and nothing the gate derived.
type confirmView struct {
	ID         string
	URL        string
	Label      bench.ExtractLabel
	Note       string
	ProposedBy string
	Title      string
	Head       string
	Mid        string

	URLsTotal    int
	URLsSameHost int
	URLsJoblike  int
}

// confirmViewOf builds a row's confirmation view. It reuses worksheetFor for the
// page text and link counts so the two review surfaces can never disagree about
// what a page says, and re-cuts the text windows wider.
func confirmViewOf(row goldRow) confirmView {
	ws := worksheetFor(row)
	main := []rune(flattenField(row.Content.MainContent))
	mid := ""
	if start := len(main) / 3; start > confirmHeadRunes {
		mid = string(main[start:min(start+confirmMidRunes, len(main))])
	}
	return confirmView{
		ID:           ws.ID,
		URL:          ws.URL,
		Label:        row.Label,
		Note:         row.LabelProvenance.Note,
		ProposedBy:   row.LabelProvenance.ProposedBy,
		Title:        ws.Title,
		Head:         truncateRunes(flattenField(row.Content.MainContent), confirmHeadRunes),
		Mid:          mid,
		URLsTotal:    ws.URLsTotal,
		URLsSameHost: ws.URLsSameHost,
		URLsJoblike:  ws.URLsJoblike,
	}
}

// orNone renders an empty field as an explicit marker, so a confirmer can tell a
// page that said nothing from a sheet that lost the text.
func orNone(s string) string {
	if strings.TrimSpace(s) == "" {
		return "(none)"
	}
	return s
}

// parseConfirmIDs parses a confirmation id file: one row id per line, blank and
// '#' lines skipped. It is what makes a chunk-by-chunk human pass reviewable --
// the diff shows exactly which rows gained a confirmer.
func parseConfirmIDs(data []byte) (map[string]struct{}, error) {
	ids := map[string]struct{}{}
	for i, line := range strings.Split(string(data), "\n") {
		id := strings.TrimSpace(line)
		if id == "" || strings.HasPrefix(id, "#") {
			continue
		}
		if strings.ContainsAny(id, " \t") {
			return nil, fmt.Errorf("confirm-ids line %d: %q is not a bare row id", i+1, id)
		}
		ids[id] = struct{}{}
	}
	if len(ids) == 0 {
		return nil, fmt.Errorf("confirm-ids names no row; an empty confirmation is not a confirmation")
	}
	return ids, nil
}
