// Code generated by "llmbench train-scorer"; DO NOT EDIT.

package pagegate

// The directive regenerates this file from the committed Extract Gold Set. It runs
// with this package's directory as its working directory, hence the relative path and
// the bare output name. It is inert until the trainer verb exists, and no CI step runs
// "go generate" -- the standing guard is instead that regenerating must reproduce this
// file byte for byte, so a weight can only move by a Gold Set change or a trainer
// change, both visible in the same diff.
//go:generate go run ../../cmd/llmbench train-scorer -out posting_score_weights_gen.go

// scoreWeights is the Score Vocabulary and the structural Score Signal weights,
// keyed by the exact names Signals emits (ADR-0049). It is the one part of
// pagegate that is fitted rather than argued, which is why it is data a human
// reads rather than a rule a human reasons about.
//
// SEEDED EMPTY. Until "llmbench train-scorer" has fitted it, every page carries no
// weighted signal at all, every Posting Score is the same number, and the artifact
// cannot move a single gate verdict.
//
// Generated Go source rather than an embedded data file, and that is a deliberate
// deviation from the repo's one precedent, internal/geo (ADR-0031): parseGazetteer
// silently skips a malformed row, and a rule deciding spend on every walked page
// must not be able to boot with a quietly truncated Score Vocabulary. Generated
// source fails at compile time instead.
var scoreWeights = map[string]float64{}

// scoreIntercept is the fitted intercept: the Posting Score, before the logistic
// squash, of a page carrying no weighted Score Signal at all.
const scoreIntercept = 0.0

// VetoThreshold is the Posting Score at or above which the Learned Veto lets a page
// through (ADR-0049). It is a value in Score's [0,1] space.
//
// Compiled in beside the weights and deliberately NOT a config field: it is the
// operating point the training run chose under the zero-detail-loss constraint, and
// letting it drift independently of the weights it was chosen against would mean
// running an operating point nobody measured.
//
// Seeded 0, so an untrained artifact is incapable of dropping a page.
const VetoThreshold float64 = 0.0
